/// <reference types="vite/client" />
import { initializeApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider, signOut, onAuthStateChanged, User } from 'firebase/auth';
import { getFirestore, collection, addDoc, updateDoc, deleteDoc, doc, query, where, onSnapshot, getDocFromServer, getDocs, orderBy, Timestamp } from 'firebase/firestore';

// Security Note: In Firebase client-side SDKs, these identifiers are intended to be public.
// They are used by the library to identify your project (like an address), but do NOT grant
// access to your data. Security is enforced via Firestore Security Rules (see `/firestore.rules`)
// and Authentication. Even if these keys are visible in the source code, no one can access
// your documents unless they satisfy the conditions in your security rules.

// Initialize Firebase with config from env variables
const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
  measurementId: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID,
  firestoreDatabaseId: import.meta.env.VITE_FIREBASE_DATABASE_ID || '(default)'
};

// Internal auto-configuration for AI Studio preview environment
// We attempt to load the local config, but don't fail if it's missing (e.g. on GitHub)
let isUsingLocalConfig = false;
try {
  // @ts-ignore - This file is automatically generated in AI Studio but might be missing on GitHub
  const localConfig = await import('../../firebase-applet-config.json');
  if (localConfig && localConfig.default) {
    const config = localConfig.default;
    firebaseConfig.apiKey = config.apiKey || firebaseConfig.apiKey;
    firebaseConfig.authDomain = config.authDomain || firebaseConfig.authDomain;
    firebaseConfig.projectId = config.projectId || firebaseConfig.projectId;
    firebaseConfig.storageBucket = config.storageBucket || firebaseConfig.storageBucket;
    firebaseConfig.messagingSenderId = config.messagingSenderId || firebaseConfig.messagingSenderId;
    firebaseConfig.appId = config.appId || firebaseConfig.appId;
    firebaseConfig.measurementId = config.measurementId || firebaseConfig.measurementId;
    if (config.firestoreDatabaseId) {
      firebaseConfig.firestoreDatabaseId = config.firestoreDatabaseId;
    }
    isUsingLocalConfig = !!config.apiKey;
  }
} catch (e) {
  // Standard development or production environment (e.g. GitHub clone)
  // Fall back entirely to environment variables
}

console.log("Firebase Config Initialization:", {
  projectId: firebaseConfig.projectId,
  hasApiKey: !!firebaseConfig.apiKey,
  hasAppId: !!firebaseConfig.appId,
  databaseId: firebaseConfig.firestoreDatabaseId,
  usingLocalConfig: isUsingLocalConfig
});

export const isFirebaseConfigured = !!firebaseConfig.apiKey;

let connectionStatus: 'idle' | 'checking' | 'connected' | 'error' = 'idle';
let connectionErrorMessage: string | null = null;
export const getConnectionStatus = () => ({ status: connectionStatus, error: connectionErrorMessage });

const app = initializeApp(firebaseConfig);
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);
export const auth = getAuth(app);
export const googleProvider = new GoogleAuthProvider();

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
  }
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid,
      email: auth.currentUser?.email,
      emailVerified: auth.currentUser?.emailVerified,
      isAnonymous: auth.currentUser?.isAnonymous,
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

// Test connection
async function testConnection() {
  if (!isFirebaseConfigured) return;
  
  connectionStatus = 'checking';
  try {
    // We try to fetch from server to verify connection and keys
    await getDocFromServer(doc(db, 'system', 'connectivity_test'));
    connectionStatus = 'connected';
    connectionErrorMessage = null;
  } catch (error: any) {
    const msg = error?.message || String(error);
    
    if (msg.includes('Database') && msg.includes('not found')) {
      connectionStatus = 'error';
      connectionErrorMessage = `Database not found. Active ID: ${firebaseConfig.firestoreDatabaseId}. This usually indicates the database is still provisioning or the ID is incorrect.`;
      console.error("Firebase Connection Error Diagnostic:", msg);
    } else if (msg.includes('the client is offline') || error?.code === 'unavailable' || msg.includes('network')) {
      connectionStatus = 'error';
      connectionErrorMessage = "Network connection failed. This usually indicates blocked cross-site tracking in your browser or a firewall issue. Try opening the app in a new tab.";
      console.warn("Firebase Connection Warning:", connectionErrorMessage);
    } else {
      // Permission denied or other errors usually mean we reached the server
      connectionStatus = 'connected';
      connectionErrorMessage = null;
    }
  }
}
testConnection();
